my:
  greeting: Generic update from config server
  list:
    values: One,Two,Three
  db:
    values: "{connectionString: 'blabalbal', userName: 'foo-server', password: 'pass-server'}"

db:
  connection: connection-string-server
  host: 127.0.0.1
  port: 1200